INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (1, 'MAYBELLINE', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (2, 'SORIANA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (3, 'WAL MART', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (4, 'VOGUE', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (5, 'ILUSION', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (6, 'SEARS', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (7, 'LIVERPOOL', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (8, 'CASA LEY', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (9, 'CHEDRAUI', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (10, 'FARMACIAS BENAVIDES', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (11, 'FARMACIA DEL AHORRO', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (12, 'COMERCIAL MEXICANA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (13, 'SANBORNS', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (14, 'L''OREAL', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (15, 'SEPHORA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (16, 'SAN PABLO', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (17, 'PALACIO DE HIERRO', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (18, 'FABRICAS DE FRANCIA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (19, 'HEB', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (20, 'FARMACIA GUADALAJARA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (21, 'FARMACIAS GDL', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (22, 'CORPORATIVO NESTLE', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (23, 'HEMSA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (24, 'FARMACIA BENAVIDES', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (25, 'SMART', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (26, 'MERCO', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (27, 'NOVEDADES Y COSMETICOS', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (28, 'NYX', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (29, 'ULTRA FEMME', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (30, 'DAX', null, null, 1);