INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (1, 'GARNIER', '01', 1, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (2, 'NYX', '02', 1, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (3, 'FARMACIAS', '03', 1, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (4, 'LOREAL', '04', 1, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (5, 'DERMO', '05', 1, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (6, 'MAYBELLINE', '06', 1, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (7, 'VOGUE', '07', 1, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (8, 'GAC', '01', 2, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (9, 'UD', '02', 2, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (10, 'V&R', '03', 2, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (11, 'YSL', '04', 2, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (12, 'PCI', '05', 2, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (13, 'LANCOME', '06', 2, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (14, 'COSMETICA ACTIVA', '01', 3, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (15, 'L''OREAL', '01', 4, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (16, 'LIVERPOOL', '02', 4, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (17, 'PALACIO DE HIERRO', '03', 4, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (18, 'SANBORNS', '04', 4, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (19, 'SEARS', '05', 4, null, null, 1);
INSERT INTO s10_brands (id, name, code, line_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (20, 'SEPHORA', '06', 4, null, null, 1);