INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (1, 'Alberto Medina Ortiz', '1', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (2, 'Mauricio Ontiveros Cruz', '2', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (3, 'Imanol Humberto Ramírez López', '3', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (4, 'Juan Carlos Pérez Escobar', '4', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (5, 'German Moreno Mendieta', '5', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (6, 'Edgar Alexander Mota', '6', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (7, 'Juan Javier Centeno Rico', '7', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (8, 'Dhey Gallardo Sanchez', '8', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (9, 'Yhael Chona Sarmina', '9', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (10, 'Miriam Amyra Cervantes Nacif', '10', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (11, 'Oscar Lopez Zerafino', '11', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (12, 'Abel Alejandro Esparza Venegas', '12', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (13, 'Andrea Monserrat Rosales Flores', '13', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (14, 'Julieta Dueñas Porras', '14', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (15, 'Lester Ivan Rios Prieto', '15', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (16, 'Leopoldo Agustín Alvarez Guillen', '16', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (17, 'Jesús Manuel López Correa', '17', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (18, 'Hector Sanchez Quevedo', '18', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (19, 'Armando Duarte Ramirez', '19', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (20, 'Daniel Sifuentes Delgado', '20', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (21, 'Gabriela Morato Alvarez', '21', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (22, 'Ramiro Esteban Ruiz Camacho', '22', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (23, 'Victor Jacobo Gallegos Vargas', '23', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (24, 'Roberto Gamaliel Lazama Javier', '24', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (25, 'María Angélica Rojas Perez', '25', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (26, 'Jose Angel Lopez Diaz', '26', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (27, 'Christian Iván Rincon Maturino', '27', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (28, 'Enrique Alberto Macias Chavez', '28', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (29, 'Francisco Peñaloza', '29', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (30, 'Roberto Carlos Sandoval Gomez', '30', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (31, 'Francisco Marcelino Gonzalez Mercado', '31', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (32, 'Manuel Ivan Montalvo Maldonado', '32', null, null, 1);
INSERT INTO s10_clerks (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (33, 'Jesús Eduardo del Villar', '33', null, null, 1);