INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (1, 'MAKEUP DESIGNER', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (2, 'MAKEUP DESIGNER COPETE NEGRO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (3, 'SPARKIST 3.60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (4, 'SPARKIST 3.60 COPETE NEGRO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (5, 'SPARKIST 2.40', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (6, 'SPARKIST 1.70 NUEVO Y ACCESORIOS', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (7, 'SPARKIST 1.70 COPETE NEGRO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (8, 'SPARKIST 1.20 NUEVO Y ACCESORIOS', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (9, 'SPARKIST 1.20 COPETE NEGRO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (10, 'SPARKLE 3.60 X 1.45', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (11, 'SPARKLE 3.60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (12, 'SPARKLE 2.40', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (13, 'SPARKLE 1.70', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (14, 'SPARKLE 1.20', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (15, 'DIAMOND 2.40', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (16, 'DIAMOND 1.70', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (17, 'DIAMOND 1.20', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (18, 'PREMIUM 4.80 X 1.45', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (19, 'PREMIUM 3.60 X 1.45', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (20, 'PREMIUM 2.40', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (21, 'PREMIUM 1.70', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (22, 'PREMIUM 1.20', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (23, 'GONDOLAS MAKE UP', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (24, 'GONDOLAS BASICA', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (25, 'GONDOLAS PREMIUM', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (26, 'BERGERIE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (27, 'PLAZA CENTRAL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (28, 'MAKE IT HAPPEN 3.60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (29, 'MAKE IT HAPPEN 2.40', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (30, 'MAKE IT HAPPEN 1.60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (31, 'CITY 3.60 X 1.45', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (32, 'CITY 3.60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (33, 'CITY 2.40 CENEFA GRANDE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (34, 'CITY 2.40 CENEFA CHICA', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (35, 'CITY 1.60 CENEFA GRANDE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (36, 'CITY 1.60 CENEFA CHICA', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (37, 'URBAN CHIC 4.80 X 1.45', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (38, 'URBAN CHIC 3.60 X 1.45', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (39, 'URBAN CHIC 3.60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (40, 'URBAN CHIC 2.40', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (41, 'URBAN CHIC 1.60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (42, 'LIP BAR / FACE BAR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (43, 'SCULPT STUDIO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (44, 'TREND BAR 1.20', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (45, 'TREND BAR 60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (46, 'NAIL BAR 1.20', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (47, 'NAIL BAR 60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (48, 'BERGERIE MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (49, 'TORRE ILUSIÓN', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (50, 'TOTEM ILUSIÓN', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (51, 'WHITE WALL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (52, 'WHITE WALL 8 FT', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (53, 'WHITE WALL 12 FT GLORIFICADOR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (54, 'WHITE WALL 14 FT GLORIFICADOR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (55, 'WHITE WALL 16 FT CHAPARRO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (56, 'WHITE WALL 16 FT GLORIFICADOR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (57, 'WHITE WALL 20 FT CHAPARRO GLORIFICADOR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (58, 'WHITE WALL 20 FT GLORIFICADOR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (59, 'SCULPT BAR (COMPARTIDO)', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (60, 'COLUMNA', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (61, 'COLUMNA MAKE IT HAPPEN', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (62, 'COLUMNA SANTA FE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (63, 'GONDOLA MAKE UP', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (64, 'GÓNDOLA BÁSICA', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (65, 'GÓNDOLA PREMIUM', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (66, 'TORRE GIRATORIA', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (67, 'VOGUE .60', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (68, 'MUEBLE 1.20', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (69, 'MUEBLE 1.80', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (70, 'DEEP TRADE 1.35', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (71, 'DEEP TRADE 1.70', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (72, 'DEEP TRADE 2.20', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (73, 'PERFOCEL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (74, 'PERFOCEL .55', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (75, 'PERFOCEL .75', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (76, 'PERFOCEL .80', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (77, 'PERFOCEL 1.0M', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (78, 'RACK PREMIUM 120X6', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (79, 'RACK PREMIUM 120X6 DOBLE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (80, 'RACK PREMIUM 120X5', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (81, 'RACK PREMIUM 120X4', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (82, 'RACK PREMIUM 120X4 DOBLE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (83, 'RACK PREMIUM 80X6', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (84, 'RACK PREMIUM 80X5', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (85, 'DERMO RACK 6N', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (86, 'DERMO RACK 5N', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (87, 'DERMO RACK 4N', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (88, 'DERMO RACK 6N 2018', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (89, 'DERMO RACK 5N 2018', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (90, 'SKIN LAB DERMO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (91, 'DERMO RACK 6N ILUSION', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (92, 'TORRE DERMO ILUSION', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (93, 'RACK PREMIUM FACE 120X4', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (94, 'RACK PREMIUM FACE 120X5', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (95, 'RACK PREMIUM FACE 120X6', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (96, 'RACK PREMIUM FACE 80X5', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (97, 'RACK PREMIUM FACE 80X6', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (98, 'RACK FACE 120X4', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (99, 'RACK FACE 120X5', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (100, 'RACK FACE 120X6N 2018', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (101, 'PERIMETRAL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (102, 'GRAB & GO', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (103, 'BEAUTY BAR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (104, 'CASH WRAP', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (105, 'WHAT''S NEW', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (106, 'GONDOLAS PERIMETRALES', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (107, 'SETS & BAGS', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (108, 'BRUSH BAR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (109, 'NICHO DE PARED', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (110, 'CAJAS DE LUZ COLUMNA', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (111, 'CABECERA FIRST LOOK', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (112, 'GÓNDOLA LIVERPOOL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (113, 'SHOPPING BASKET', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (114, 'WALL DAX', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (115, 'CABECERA PRO BAR DAX', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (116, 'PERIMETRAL LIVERPOOL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (117, 'TORRE LIVERPOOL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (118, 'BANCO BEAUTY BAR', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (119, 'PHARMA PLUS 3 TRAMOS LOREAL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (120, 'PHARMA PLUS 3 TRAMOS MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (121, 'PHARMA PLUS 5&6 TRAMOS LOREAL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (122, 'PHARMA PLUS 5 TRAMOS MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (123, 'PHARMA PLUS 6 TRAMOS MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (124, 'CLEAN&BRIGHT NSE ALTO 3 TRAMOS MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (125, 'CLEAN&BRIGHT NSE ALTO 3 TRAMOS LOREAL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (126, 'CLEAN&BRIGHT NSE ALTO 4 TRAMOS MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (127, 'CLEAN&BRIGHT NSE ALTO 4 TRAMOS LOREAL', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (128, 'CLEAN&BRIGHT NSE BAJO 3 TRAMOS MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (129, 'CLEAN&BRIGHT NSE BAJO 3 TRAMOS VOGUE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (130, 'CLEAN&BRIGHT NSE BAJO 4 TRAMOS MAYBELLINE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (131, 'CLEAN&BRIGHT NSE BAJO 4 TRAMOS VOGUE', null, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, reg_created_dt, reg_updated_dt, reg_status) VALUES (132, 'ISLA', null, null, null, 1);