INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (1, 'AGUASCALIENTES', '1', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (2, 'BAJA CALIFORNIA NORTE', '2', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (3, 'BAJA CALIFORNIA SUR', '3', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (4, 'CAMPECHE', '4', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (5, 'CHIAPAS', '5', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (6, 'CHIHUAHUA', '6', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (7, 'DISTRITO FEDERAL', '7', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (8, 'COAHUILA', '8', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (9, 'COLIMA', '9', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (10, 'DURANGO', '10', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (11, 'ESTADO DE MEXICO', '11', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (12, 'GUANAJUATO', '12', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (13, 'GUERRERO', '13', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (14, 'HIDALGO', '14', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (15, 'JALISCO', '15', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (16, 'MICHOACAN', '16', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (17, 'MORELOS', '17', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (18, 'NAYARIT', '18', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (19, 'NUEVO LEON', '19', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (20, 'OAXACA', '20', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (21, 'PUEBLA', '21', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (22, 'QUERETARO', '22', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (23, 'QUINTANA ROO', '23', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (24, 'SAN LUIS POTOSI', '24', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (25, 'SINALOA', '25', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (26, 'SONORA', '26', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (27, 'TABASCO', '27', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (28, 'TAMAULIPAS', '28', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (29, 'TLAXCALA', '29', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (30, 'VERACRUZ', '30', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (31, 'YUCATAN', '31', null, null, 1);
INSERT INTO s10_states (id, name, code, reg_created_dt, reg_updated_dt, reg_status) VALUES (32, 'ZACATECAS', '32', null, null, 1);