INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (1, 'MAYBELLINE', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (2, 'COMERCIAL MEXICANA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (3, 'VOGUE', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (4, 'SORIANA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (5, 'SANBORNS', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (6, 'WAL MART', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (7, 'ILUSION', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (8, 'FARMACIAS BENAVIDES', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (9, 'CHEDRAUI', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (10, 'LIVERPOOL', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (11, 'SEARS', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (12, 'L''OREAL', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (13, 'SEPHORA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (14, 'SAN PABLO', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (15, 'PALACIO DE HIERRO', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (16, 'FABRICAS DE FRANCIA', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (17, 'CASA LEY', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (18, 'HEB', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (19, 'NYX', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (20, 'DAX', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (21, 'FARMACIA DEL AHORRO', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (22, 'ULTRA FEMME', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (23, 'CORPORATIVO NESTLE', null, null, 1);
INSERT INTO s10_chain_stores (id, name, reg_created_dt, reg_updated_dt, reg_status) VALUES (24, 'COSMETICA ACTIVA', null, null, 1);