INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (1, 'MAKEUP DESIGNER', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (2, 'MAKEUP DESIGNER COPETE NEGRO', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (3, 'SPARKIST 3.60', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (4, 'SPARKIST 3.60 COPETE NEGRO', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (5, 'SPARKIST 2.40', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (6, 'SPARKIST 1.70 NUEVO Y ACCESORIOS', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (7, 'SPARKIST 1.70 COPETE NEGRO', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (8, 'SPARKIST 1.20 NUEVO Y ACCESORIOS', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (9, 'SPARKIST 1.20 COPETE NEGRO', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (10, 'SPARKLE 3.60 X 1.45', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (11, 'SPARKLE 3.60', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (12, 'SPARKLE 2.40', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (13, 'SPARKLE 1.70', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (14, 'SPARKLE 1.20', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (15, 'DIAMOND 2.40', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (16, 'DIAMOND 1.70', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (17, 'DIAMOND 1.20', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (18, 'PREMIUM 4.80 X 1.45', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (19, 'PREMIUM 3.60 X 1.45', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (20, 'PREMIUM 2.40', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (21, 'PREMIUM 1.70', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (22, 'PREMIUM 1.20', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (23, 'GONDOLAS MAKE UP', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (24, 'GONDOLAS BASICA', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (25, 'GONDOLAS PREMIUM', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (26, 'BERGERIE', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (27, 'PLAZA CENTRAL', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (28, 'MAKE IT HAPPEN 3.60', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (29, 'MAKE IT HAPPEN 2.40', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (30, 'MAKE IT HAPPEN 1.60', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (31, 'CITY 3.60 X 1.45', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (32, 'CITY 3.60', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (33, 'CITY 2.40 CENEFA GRANDE', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (34, 'CITY 2.40 CENEFA CHICA', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (35, 'CITY 1.60 CENEFA GRANDE', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (36, 'CITY 1.60 CENEFA CHICA', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (37, 'URBAN CHIC 4.80 X 1.45', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (38, 'URBAN CHIC 3.60 X 1.45', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (39, 'URBAN CHIC 3.60', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (40, 'URBAN CHIC 2.40', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (41, 'URBAN CHIC 1.60', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (42, 'LIP BAR / FACE BAR', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (43, 'SCULPT STUDIO', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (44, 'TREND BAR 1.20', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (45, 'TREND BAR 60', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (46, 'NAIL BAR 1.20', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (47, 'NAIL BAR 60', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (48, 'BERGERIE MAYBELLINE', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (49, 'TORRE ILUSIÓN', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (50, 'TOTEM ILUSIÓN', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (51, 'WHITE WALL', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (52, 'WHITE WALL 8 FT', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (53, 'WHITE WALL 12 FT GLORIFICADOR', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (54, 'WHITE WALL 14 FT GLORIFICADOR', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (55, 'WHITE WALL 16 FT CHAPARRO', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (56, 'WHITE WALL 16 FT GLORIFICADOR', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (57, 'WHITE WALL 20 FT CHAPARRO GLORIFICADOR', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (58, 'WHITE WALL 20 FT GLORIFICADOR', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (59, 'SCULPT BAR (COMPARTIDO)', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (60, 'SCULPT BAR (COMPARTIDO)', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (61, 'COLUMNA', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (62, 'COLUMNA', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (63, 'COLUMNA MAKE IT HAPPEN', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (64, 'COLUMNA MAKE IT HAPPEN', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (65, 'COLUMNA SANTA FE', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (66, 'COLUMNA SANTA FE', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (67, 'GONDOLA MAKE UP', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (68, 'GONDOLA MAKE UP', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (69, 'GÓNDOLA BÁSICA', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (70, 'GÓNDOLA BÁSICA', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (71, 'GÓNDOLA PREMIUM', null, 4, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (72, 'GÓNDOLA PREMIUM', null, 6, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (73, 'TORRE GIRATORIA', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (74, 'VOGUE .60', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (75, 'MUEBLE 1.20', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (76, 'MUEBLE 1.80', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (77, 'DEEP TRADE 1.35', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (78, 'DEEP TRADE 1.70', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (79, 'DEEP TRADE 2.20', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (80, 'PERFOCEL', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (81, 'PERFOCEL .55', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (82, 'PERFOCEL .75', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (83, 'PERFOCEL .80', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (84, 'PERFOCEL 1.0M', null, 7, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (85, 'RACK PREMIUM 120X6', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (86, 'RACK PREMIUM 120X6 DOBLE', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (87, 'RACK PREMIUM 120X5', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (88, 'RACK PREMIUM 120X4', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (89, 'RACK PREMIUM 120X4 DOBLE', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (90, 'RACK PREMIUM 80X6', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (91, 'RACK PREMIUM 80X5', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (92, 'DERMO RACK 6N', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (93, 'DERMO RACK 5N', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (94, 'DERMO RACK 4N', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (95, 'DERMO RACK 6N 2018', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (96, 'DERMO RACK 5N 2018', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (97, 'SKIN LAB DERMO', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (98, 'DERMO RACK 6N ILUSION', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (99, 'TORRE DERMO ILUSION', null, 5, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (100, 'RACK PREMIUM FACE 120X4', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (101, 'RACK PREMIUM FACE 120X5', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (102, 'RACK PREMIUM FACE 120X6', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (103, 'RACK PREMIUM FACE 80X5', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (104, 'RACK PREMIUM FACE 80X6', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (105, 'RACK FACE 120X4', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (106, 'RACK FACE 120X5', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (107, 'RACK FACE 120X6N 2018', null, 1, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (108, 'PERIMETRAL', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (109, 'GRAB & GO', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (110, 'BEAUTY BAR', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (111, 'CASH WRAP', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (112, 'WHAT''S NEW', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (113, 'GONDOLAS PERIMETRALES', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (114, 'SETS & BAGS', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (115, 'BRUSH BAR', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (116, 'NICHO DE PARED', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (117, 'COLUMNA', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (118, 'CAJAS DE LUZ COLUMNA', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (119, 'CABECERA FIRST LOOK', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (120, 'GÓNDOLA LIVERPOOL', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (121, 'SHOPPING BASKET', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (122, 'WALL DAX', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (123, 'CABECERA PRO BAR DAX', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (124, 'PERIMETRAL LIVERPOOL', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (125, 'TORRE LIVERPOOL', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (126, 'BANCO BEAUTY BAR', null, 2, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (127, 'PHARMA PLUS 3 TRAMOS LOREAL', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (128, 'PHARMA PLUS 3 TRAMOS MAYBELLINE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (129, 'PHARMA PLUS 5&6 TRAMOS LOREAL', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (130, 'PHARMA PLUS 5 TRAMOS MAYBELLINE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (131, 'PHARMA PLUS 6 TRAMOS MAYBELLINE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (132, 'CLEAN&BRIGHT NSE ALTO 3 TRAMOS MAYBELLINE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (133, 'CLEAN&BRIGHT NSE ALTO 3 TRAMOS LOREAL', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (134, 'CLEAN&BRIGHT NSE ALTO 4 TRAMOS MAYBELLINE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (135, 'CLEAN&BRIGHT NSE ALTO 4 TRAMOS LOREAL', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (136, 'CLEAN&BRIGHT NSE BAJO 3 TRAMOS MAYBELLINE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (137, 'CLEAN&BRIGHT NSE BAJO 3 TRAMOS VOGUE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (138, 'CLEAN&BRIGHT NSE BAJO 4 TRAMOS MAYBELLINE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (139, 'CLEAN&BRIGHT NSE BAJO 4 TRAMOS VOGUE', null, 3, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (140, 'ISLA', null, 8, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (141, 'ISLA', null, 9, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (142, 'ISLA', null, 10, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (143, 'ISLA', null, 11, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (144, 'ISLA', null, 12, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (145, 'ISLA', null, 13, null, null, 1);
INSERT INTO s10_furniture_types (id, name, description, brand_id, reg_created_dt, reg_updated_dt, reg_status) VALUES (146, 'ISLA', null, 14, null, null, 1);