<?php
/**
 * Created by IntelliJ IDEA.
 * User: alberto
 * Date: 26/11/18
 * Time: 04:14 PM
 */

namespace App\Consts;

/**
 * Class Http
 * @package App\Consts
 */
class Http
{
    const HEADER_CORS = 'Access-Control-Allow-Origin';
    const HEADER_CONTENT_TYPE = 'Content-Type';
    const HEADER_AUTHORIZATION = 'authorization';

    const CONTENT_TYPE_APPLICATION_JSON_UTF8 = 'application/json; charset=utf-8';
    const CONTENT_TYPE_APPLICATION_XML = 'application/xml';
    const CONTENT_TYPE_APPLICATION_PDF = 'application/pdf';
    const CONTENT_TYPE_TEXT_HTML_UTF8 = 'text/html; charset=utf-8';
    const CONTENT_TYPE_APPLICATION_ZIP_OCTET_STREAM = 'application/zip, application/octet-stream';
    const CONTENT_TYPE_APPLICATION_SPREADSHEET = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    const CONTENT_TYPE_IMAGE_SVG_XML = 'image/svg+xml';

    const STATUS_CODE_HTTP_CONTINUE = 100;
    const STATUS_CODE_HTTP_SWITCHING_PROTOCOLS = 101;
    const STATUS_CODE_HTTP_PROCESSING = 102; // RFC2518
    const STATUS_CODE_HTTP_EARLY_HINTS = 103; // RFC8297
    const STATUS_CODE_HTTP_OK = 200;
    const STATUS_CODE_HTTP_CREATED = 201;
    const STATUS_CODE_HTTP_ACCEPTED = 202;
    const STATUS_CODE_HTTP_NON_AUTHORITATIVE_INFORMATION = 203;
    const STATUS_CODE_HTTP_NO_CONTENT = 204;
    const STATUS_CODE_HTTP_RESET_CONTENT = 205;
    const STATUS_CODE_HTTP_PARTIAL_CONTENT = 206;
    const STATUS_CODE_HTTP_MULTI_STATUS = 207; // RFC4918
    const STATUS_CODE_HTTP_ALREADY_REPORTED = 208; // RFC5842
    const STATUS_CODE_HTTP_IM_USED = 226; // RFC3229
    const STATUS_CODE_HTTP_MULTIPLE_CHOICES = 300;
    const STATUS_CODE_HTTP_MOVED_PERMANENTLY = 301;
    const STATUS_CODE_HTTP_FOUND = 302;
    const STATUS_CODE_HTTP_SEE_OTHER = 303;
    const STATUS_CODE_HTTP_NOT_MODIFIED = 304;
    const STATUS_CODE_HTTP_USE_PROXY = 305;
    const STATUS_CODE_HTTP_RESERVED = 306;
    const STATUS_CODE_HTTP_TEMPORARY_REDIRECT = 307;
    const STATUS_CODE_HTTP_PERMANENTLY_REDIRECT = 308; // RFC7238
    const STATUS_CODE_HTTP_BAD_REQUEST = 400;
    const STATUS_CODE_HTTP_UNAUTHORIZED = 401;
    const STATUS_CODE_HTTP_PAYMENT_REQUIRED = 402;
    const STATUS_CODE_HTTP_FORBIDDEN = 403;
    const STATUS_CODE_HTTP_NOT_FOUND = 404;
    const STATUS_CODE_HTTP_METHOD_NOT_ALLOWED = 405;
    const STATUS_CODE_HTTP_NOT_ACCEPTABLE = 406;
    const STATUS_CODE_HTTP_PROXY_AUTHENTICATION_REQUIRED = 407;
    const STATUS_CODE_HTTP_REQUEST_TIMEOUT = 408;
    const STATUS_CODE_HTTP_CONFLICT = 409;
    const STATUS_CODE_HTTP_GONE = 410;
    const STATUS_CODE_HTTP_LENGTH_REQUIRED = 411;
    const STATUS_CODE_HTTP_PRECONDITION_FAILED = 412;
    const STATUS_CODE_HTTP_REQUEST_ENTITY_TOO_LARGE = 413;
    const STATUS_CODE_HTTP_REQUEST_URI_TOO_LONG = 414;
    const STATUS_CODE_HTTP_UNSUPPORTED_MEDIA_TYPE = 415;
    const STATUS_CODE_HTTP_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    const STATUS_CODE_HTTP_EXPECTATION_FAILED = 417;
    const STATUS_CODE_HTTP_I_AM_A_TEAPOT = 418; // RFC2324
    const STATUS_CODE_HTTP_MISDIRECTED_REQUEST = 421; // RFC7540
    const STATUS_CODE_HTTP_UNPROCESSABLE_ENTITY = 422; // RFC4918
    const STATUS_CODE_HTTP_LOCKED = 423; // RFC4918
    const STATUS_CODE_HTTP_FAILED_DEPENDENCY = 424; // RFC4918
}